version: '3.8'

services:
  client-gateway-nestjs:
    build: ./client_gateway_nestjs
    ports:
      - "3000:3000"
    volumes:
      - ./client_gateway_nestjs/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats:4222